In [1]:
import networkx as nx
import plotly.graph_objects as go
import pandas as pd
import random
import numpy as np
import matplotlib.pyplot as plt

In [2]:
n, k, p, q , MinOutsideWeight, MaxOutsideWeight, MinInsideWeight, MaxInsideWeight = input().split()
C = np.zeros(int(k))
M = np.zeros((int(n),int(n)))

for i in range(int(k)):
    C[i] = int(input())

In [3]:
t = 0
cnt = 0
Graph = []
for i in range(int(n)):
    if(i >= cnt + C[t]):
        cnt += C[t]
        t += 1
    for j in range(i):
        if(j >= cnt):
            x = random.random()
            if(x <= float(p)):
                y = random.random()
                y *= (int(MaxInsideWeight) - int(MinInsideWeight))
                y += int(MinInsideWeight)
                M[i][j] = M[j][i] = y
                temp = [i, j]
                Graph.append(temp)
        else:
            x = random.random()
            if(x <= float(q)):
                y = random.random()
                y *= (int(MaxOutsideWeight) - int(MinOutsideWeight))
                y += int(MinOutsideWeight)
                M[i][j] = M[j][i] = y
                temp = [i, j]
                Graph.append(temp)

In [4]:
print(M)

[[0.         0.         1.49177478 2.25520807]
 [0.         0.         2.29977263 2.67377882]
 [1.49177478 2.29977263 0.         5.84623851]
 [2.25520807 2.67377882 5.84623851 0.        ]]
